### ISSUE TITLE
Enhancement: validate path given in --infile option

### ISSUE THREAD

**Issue by timhutch** [BitCurator/bitcurator-nlp-gentm#8]
Running python bcnlp_tm.py --infile=/path/to/my/files:

A useful enhancement would be to halt the process and return an error if the value of --infile is not valid (directory doesn't exist). If there is an error in the directory name, you get the error "Input sa is not an SArray", which isn't really helpful and could be the result of other problems.

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
